version: "3.9"

services:
  db:
    hostname: ${POSTGRES_HOST_NAME}
    container_name: pgvector_db_container
    image: ankane/pgvector
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - ${PGADMIN_PORT}:80
    user: "$UID:$GID"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   environment:
  #     DATABASE_URL: ${DOCKER_SQLALCHEMY_DATABASE_URL}
  #     REDIS_URL: ${REDIS_URL}
  #   ports:
  #     - "${APP_PORT}:8000"
  #   volumes:
  #     - .:/app

volumes:
  local_pgdata:
  pgadmin-data: