"""Changes

Revision ID: efe5fde3050a
Revises: 0265f47d2c0c
Create Date: 2024-09-17 19:41:13.033650

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe5fde3050a'
down_revision: Union[str, None] = '0265f47d2c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('document_name', sa.String(), nullable=False))
    op.drop_column('chats', 'text')
    op.drop_column('chats', 'collection_id')
    op.add_column('documents', sa.Column('document_name', sa.String(), nullable=False))
    op.drop_index('idx_documents_embedding', table_name='documents', postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_documents_embedding', 'documents', ['embedding'], unique=False, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_column('documents', 'document_name')
    op.add_column('chats', sa.Column('collection_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chats', 'document_name')
    # ### end Alembic commands ###
